solicitante:
  nome: "siga"
  sobrenome: "DevSecOps"

homologacao:
  pre_aprovado: true
  restricao_horario_inicio: "00:00"
  restricao_horario_fim: "23:59"
  
treinamento:
  pre_aprovado: true
  restricao_horario_inicio: "00:00"
  restricao_horario_fim: "23:59"

producao:
  pre_aprovado: false
  restricao_horario_inicio: "23:00"
  restricao_horario_fim: "23:59"
