swagger: '2.0'

info:
  version: "1.0.0"
  title: ExApiV1
  description: API para o Siga-Doc 

basePath: /sigaex/api/v1
schemes: [http,https]
consumes: [application/json,application/x-www-form-urlencoded]
produces: [application/json]

tags:
  - name: auth
    description: Autenticação
  - name: download
    description: Download
    
securityDefinitions:
  Basic:
    type: basic
  Bearer:
    type: apiKey
    name: Authorization
    in: header

################################################################################
#                                   Parameters                                 #
################################################################################
parameters:
  sigla:
    name: sigla
    in: path
    description: Sigla do mobil
    type: string
    required: true
  completo:
    name: completo
    in: query
    description: Informar true se deseja receber todos os arquivos juntados e anexos
    required: false
    type: boolean
  estampa:
    name: estampa
    in: query
    description: Informar true se deseja receber o PDF sem estampas
    required: false
    type: boolean
  volumes:
    name: volumes
    in: query
    description: Informar true se deseja receber uma compilação com todos os volumes de um processo
    required: false
    type: boolean
  pdf:
    name: pdf
    in: path
    description: Referência para o PDF que foi enviado previamente para o servidor
    type: string
    required: true
  jwt:
    name: jwt
    in: path
    description: JWT que referencia um artefato a ser baixado
    required: true
    type: string
  filename:
    name: filename
    in: path
    description: Nome do arquivo de um artefato a ser baixado
    required: true
    type: string
  disposition:
    name: disposition
    in: query
    description: Informar attachment se desejar receber como um download
    required: false
    type: string
  contenttype:
    name: contenttype
    in: query
    description: Informar o tipo de arquivo desejado, pode ser application/pdf ou text/html
    required: false
    type: string
  chave:
    name: chave
    in: path
    description: Chave que referencia um processo assíncrono
    required: true
    type: string
  idLotacaoIni:
    name: idLotacaoIni
    in: path
    description: Identificador da Lotação Inicial
    required: true
    type: string        
  id:
    name: id
    in: path
    description: Número de identificação do registro
    type: string
    required: true
  descricao:
    name: descricao
    in: query
    description: Descrição
    required: false
    type: string
  descricaoDetalhada:
    name: descricaoDetalhada
    in: query
    description: Descrição detalhada
    required: false
    type: string
  idGrupoMarcador:
    name: idGrupoMarcador
    in: query
    description: Id do grupo do marcador
    required: false
    type: string
  cor:
    name: cor
    in: query
    description: Cor em código hexa
    required: false
    type: string
  icone:
    name: icone
    in: query
    description: Nome do ícone Fontawesome
    required: false
    type: string
  tipoAplicacao:
    name: tipoAplicacao
    in: query
    description: Tipo de aplicação desejado (via ou volume em que será aplicado o marcador)
    required: false
    type: string
    default: Geral
    enum:
      - Geral
      - Em todas as vias
      - Via específica ou último volume
  tipoDataPlanejada:
    name: tipoDataPlanejada
    in: query
    description: Tipo de exibição da data planejada desejado
    required: false
    type: string
    default: Desativada
    enum:
      - Desativada
      - Opcional
      - Obrigatória
  tipoDataLimite:
    name: tipoDataLimite
    in: query
    description: Tipo de exibição da data limite desejado
    required: false
    type: string
    default: Desativada
    enum:
      - Desativada
      - Opcional
      - Obrigatória
  tipoExibicao:
    name: tipoExibicao
    in: query
    description: Tipo de exibição desejado (momento em que o marcador será aplicado)
    required: false
    type: string
    default: Imediata
    enum:
      - Imediata
      - Na data limite
      - Na data planejada
  tipoJustificativa:
    name: tipoJustificativa
    in: query
    description: Tipo de exibição da justificativa desejado
    required: false
    type: string
    default: Desativada
    enum:
      - Desativada
      - Opcional
      - Obrigatória
  tipoInteressado:
    name: tipoInteressado
    in: query
    description: Tipo de exibição do interessado
    required: false
    type: string
    default: Atendente
    enum:
      - Atendente
      - Pessoa
      - Lotação
      - Pessoa ou lotação
      - Lotação ou pessoa

################################################################################
#                                           Paths                              #
################################################################################
paths:
  /autenticar:
    post:
      summary: Recebe login e senha e gera um token JWT para ser usado nos outros métodos da API
      tags: [auth]
      security:
        - Basic: []
      parameters: []
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              token:
                type: string
                description: Token JWT
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"
  /documento/{sigla}/arquivo:
    get:
      summary: Inicia o processo de geração do PDF completo de um documento para visualização
      tags: [download]
      security:
        - Bearer: []
      parameters:
        - $ref: "#/parameters/contenttype"
        - $ref: "#/parameters/sigla"
        - $ref: "#/parameters/estampa"
        - $ref: "#/parameters/completo"
        - $ref: "#/parameters/volumes"
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              uuid:
                type: string
                description: UUID que pode ser usado como chave para obter status da geração do PDF
              jwt:
                type: string
                description: JWT com as informações para download do PDF
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"

  /download/{jwt}/{filename}:
    get:
      summary: Faz o download de um artefato qualquer, baseado nas informações contidas em um JWT
      tags: [download]
      parameters:
        - $ref: "#/parameters/jwt"
        - $ref: "#/parameters/filename"
        - $ref: "#/parameters/disposition"
      responses:
        200:
          description: Successful response
          schema:
            type: file
          headers:
            Content-Type:
              type: string
              description: application/pdf
            Content-Disposition:
              type: string
              description: attachment
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"
            
  /status/{chave}:
    get:
      tags: [download]
      parameters:
        - $ref: "#/parameters/chave"
      summary: Obtem o status de uma operação assíncrona
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              mensagem:
                type: string
                description: Mensagem
              indice:
                type: number
                description: Quantos passos já foram executados
              contador:
                type: number
                description: Número total de passos a serem executados
              bytes:
                type: number
                description: Tamanho total do payload até o momento
              errormsg:
                type: string
                description: Mensagem de erro se houver
              stacktrace:
                type: string
                description: Detalhamento do erro
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"

  /lotacoes/{idLotacaoIni}/marcadores:
    get:
      summary: Devolve uma lista de marcadores de uma lotação
      tags: [marcadores]
      security:
        - Bearer: []
      parameters:
        - $ref: "#/parameters/idLotacaoIni"
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              list:
                type: array
                items:
                  $ref: "#/definitions/Marcador"
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"

  /marcadores/{id}:
    get:
      summary: Devolve os dados de um marcador
      tags: [marcadores]
      security:
        - Bearer: []
      parameters:
        - $ref: "#/parameters/id"
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              marcador:
                $ref: "#/definitions/Marcador"
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"

  /marcadores:
    post:
      summary: Cria um marcador da lotação
      tags: [marcadores]
      security:
        - Bearer: []
      parameters:
        - $ref: "#/parameters/descricao"
        - $ref: "#/parameters/descricaoDetalhada"
        - $ref: "#/parameters/idGrupoMarcador"
        - $ref: "#/parameters/cor"
        - $ref: "#/parameters/icone"
        - $ref: "#/parameters/tipoAplicacao"
        - $ref: "#/parameters/tipoDataPlanejada"
        - $ref: "#/parameters/tipoDataLimite"
        - $ref: "#/parameters/tipoExibicao"
        - $ref: "#/parameters/tipoJustificativa"
        - $ref: "#/parameters/tipoInteressado"
        
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              id:
                type: string
                description: Id do marcador criado
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"

  /marcadores/{id}:
    post:
      summary: Edita um marcador da lotação
      tags: [marcadores]
      security:
        - Bearer: []
      parameters:
        - $ref: "#/parameters/id"
        - $ref: "#/parameters/descricao"
        - $ref: "#/parameters/descricaoDetalhada"
        - $ref: "#/parameters/idGrupoMarcador"
        - $ref: "#/parameters/cor"
        - $ref: "#/parameters/icone"
        - $ref: "#/parameters/tipoAplicacao"
        - $ref: "#/parameters/tipoDataPlanejada"
        - $ref: "#/parameters/tipoDataLimite"
        - $ref: "#/parameters/tipoExibicao"
        - $ref: "#/parameters/tipoJustificativa"
        - $ref: "#/parameters/tipoInteressado"
        
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              id:
                type: string
                description: Id do marcador alterado
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"


################################################################################
#                                     Definitions                              #
################################################################################
definitions:
  Status:
    type: object
    properties:
      mensagem:
        type: string
        description: Mensagem
      indice:
        type: number
        description: Quantos passos já foram executados
      contador:
        type: number
        description: Número total de passos a serem executados
      bytes:
        type: number
        description: Tamanho total do payload até o momento
      errormsg:
        type: string
        description: Mensagem de erro se houver
      stacktrace:
        type: string
        description: Detalhamento do erro

  Error:
    type: object
    properties:
      errormsg:
        type: string
  Marcador:
    description: Dados de um marcador
    type: object
    properties:
      idMarcador:
        type: string
      descricao:
        type: string
      descricaoDetalhada:
        type: string
      ativo:
        type: boolean
      tipoAplicacao:
        type: string
      tipoDataPlanejada:
        type: string
      tipoDataLimite:
        type: string
      tipoExibicao:
        type: string
      tipoJustificativa:
        type: string
      tipoInteressado:
        type: string
